name: PublishPost
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install jekyll
    - run: bundle exec jekyll build  
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: production-promotion