name: PublishPost
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install jekyll
    - run: bundle exec jekyll build
    - run: |
        git clone --single-branch --depth 1 https://github.com/omarrodriguez15/omarrodriguez15.github.io.git temprepo
        cd temprepo
        git checkout -b automated-generated-site-changes
        cd ..
        ls
        cp -rf _site/ temprepo
        cd temprepo
        
        echo "in temprepo "
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        echo "try get status"
        if [ -z "$(git status --porcelain)" ]; then
            # Working directory is clean
            echo "No changes detected "
        else
            # Uncommitted changes
            git add -A
            git commit --message "woo it finally worked"
            git push origin automated-generated-site-changes 
        fi

        echo "Copying complete 👌"